### ISSUE TITLE
[FEAUTRE] 패키지 세팅 및 CRA 초기세팅 

### ISSUE THREAD

**Issue by Mnseo** [DONGA-ST-E/Frontend#1]
## 이슈 번호
#1

## 작업 내용
- [x]  리액트 초기구성 (CRA)

## 참고사항
CRA 사용하는지 webpack이나 babel 같은거 사용하는지 시작 전에 알려주세요 💬

**Comment by hoyyChoi** [comment]
@MinseoShindor CRA 사용해서 생성할 예정입니다!

**Comment by Mnseo** [comment]
오후 2시 완료.. 슈퍼 fast
